api_version = "2026-04"

[[extensions]]
name = "Checkout Upsell"
handle = "checkout-upsell-ui"
type = "ui_extension"
uid = "078d0274-ee66-5376-f34d-097d1c3f5940c0651c14"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "$app"
key = "requestedFreeGift"
